/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aqrlei_sample_jnisample_JniTest_Companion */

#ifndef _Included_com_aqrlei_sample_jnisample_JniTest_Companion
#define _Included_com_aqrlei_sample_jnisample_JniTest_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
