/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aqrlei_sample_jnisample_JniTest */

#ifndef _Included_com_aqrlei_sample_jnisample_JniTest
#define _Included_com_aqrlei_sample_jnisample_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aqrlei_sample_jnisample_JniTest
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aqrlei_sample_jnisample_JniTest_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_aqrlei_sample_jnisample_JniTest
 * Method:    setStringToJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aqrlei_sample_jnisample_JniTest_setStringToJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
